name: ci

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: HLint Check
      uses: haskell-actions/hlint-setup@v2
      with:
        version: 'latest'

    - name: Run HLint
      run: hlint __lang/Haskell/src/

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4'

    - name: Compile check
      run: |
        mkdir -p __lang/Haskell/out
        ghc -isrc -o __lang/Haskell/out/my-app __lang/Haskell/src/Main.hs -outputdir __lang/Haskell/out

    - name: Run test
      run: ./__lang/Haskell/out/my-app | grep -q "Haskell is running"
