name: docker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: HLint Check
      uses: haskell-actions/hlint-setup@v2
      with:
        version: 'latest'

    - name: Run HLint
      run: hlint __lang/Haskell/src/

    - name: Build Docker image
      run: docker build -t haskell-app __lang/Haskell/

    - name: Run and check output
      run: |
        OUTPUT=$(docker run --rm haskell-app)
        echo "$OUTPUT"
        echo "$OUTPUT" | grep -q "Haskell is running"
