name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  quality-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (1.95)
        run: |
          rustup update stable
          rustup default 1.95
          rustup component add rustfmt clippy llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Formatting (rustfmt)
        run: cd __lang/Rust && cargo fmt --all -- --check

      - name: Deep Lint (Clippy)
        run: cd __lang/Rust && cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Tests and Generate HTML Report
        run: cd __lang/Rust && cargo llvm-cov --all-features --html

      - name: Preparation for HTML Deploy
        run: |
          # В llvm-cov отчеты по дефолту падают в target/llvm-cov/html
          cd __lang/Rust && touch target/llvm-cov/html/.nojekyll

      - name: Deploy Coverage Report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/llvm-cov/html
          git-config-name: "github-actions[bot]"
          git-config-email: "github-actions[bot]@://github.com"
          single-commit: true
